Repository vacuumlabs/adalite, pull requests merged in 2021-04, with the labels that each got.

#915 Send and delegate connect refactor
  app/frontend/actions.ts
  app/frontend/actions/error.ts
  app/frontend/components/pages/accounts/delegationModal.tsx
  app/frontend/components/pages/accounts/sendTransactionModal.tsx
  app/frontend/components/pages/delegations/delegateInput.tsx
  app/frontend/components/pages/delegations/delegatePage.tsx
  app/frontend/components/pages/delegations/stakePoolInfo.tsx
  app/frontend/components/pages/sendAda/sendAdaPage.tsx
  app/frontend/state.ts
  app/frontend/types.ts
Labels: refactor

#881 Extend pool recommendation API
  app/frontend/state.ts
  app/frontend/types.ts
  app/frontend/wallet/backend-types.ts
  app/frontend/wallet/blockchain-explorer.ts
  app/tests/src/common/mock.js
Labels: on hold

#938 Memoized useActions
  app/frontend/components/pages/delegations/delegatePage.tsx
  app/frontend/helpers/connect.ts
Labels: refactor

#954 Bring back big delegator private message
  app/frontend/actions/general.ts
  app/frontend/actions/wallet.ts
  app/frontend/components/common/alert.tsx
  app/frontend/components/pages/dashboard/dashboardPage.tsx
  app/frontend/components/pages/login/wantedAddressesModal.tsx
  app/frontend/state.ts
  app/frontend/wallet/constants.ts
  app/public/css/styles.css
Labels: high priority, needs review

#953 Refactor caching of transaction plans
  app/frontend/actions/common.ts
  app/frontend/actions/delegate.ts
  app/frontend/actions/poolOwner.ts
  app/frontend/actions/send.ts
  app/frontend/actions/transaction.ts
  app/frontend/components/pages/delegations/delegatePage.tsx
  app/frontend/components/pages/delegations/deregisterStakeKey.tsx
  app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
  app/frontend/components/pages/sendAda/sendAdaPage.tsx
  app/frontend/state.ts
  app/frontend/types.ts
Labels: refactor

#958 Webpack hot reloading
  .circleci/config.yml
  .eslintrc
  README.md
  app/.eslintrc
  app/frontend/walletApp.js
  app/package.json
  app/tests/src/common/address-manager-settings.js
  app/webpack.build.config.js
  app/yarn.lock
  package.json
  server/hotReload.js
  server/index.js
  webpack.build.config.js
  webpack.test.config.js
  yarn.lock
Labels: refactor

#959 Refactoring README
  README.md
Labels: refactor

#963 Remove connect from chosen components
  README.md
  app/frontend/components/common/loadingOverlay.tsx
  app/frontend/components/pages/accounts/accountDropdown.tsx
  app/frontend/components/pages/accounts/accountTile.tsx
  app/frontend/components/pages/accounts/accountsDashboard.tsx
  app/frontend/components/pages/dashboard/dashboardPage.tsx
Labels: refactor

#964 Fix incorrect styles order in development
  webpack.build.config.js
Labels: bug

#967 Delegate transaction refactor
  app/frontend/actions/delegate.ts
  app/frontend/actions/poolOwner.ts
  app/frontend/components/pages/delegations/delegatePage.tsx
  app/frontend/components/pages/delegations/shelleyBalances.tsx
  app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
  app/tests/src/actions/transaction-actions.js
Labels: refactor

#970 Remove 20 accounts limit for trezor
  app/frontend/wallet/shelley-wallet.ts
Labels: high priority, needs review

#965 CSS modules
  app/declaration.d.ts
  app/frontend/components/common/balance.module.scss
  app/frontend/components/common/balance.tsx
  app/frontend/variables.scss
  app/public/css/0-767px.css
  app/public/css/1024-1112px.css
  app/public/css/styles.css
  package.json
  server/index.js
  webpack.build.config.js
  yarn.lock
Labels: refactor
